prefix = "<#767ee8>Basics <white>»"
command-broadcast = "<reset><newline><#767ee8>Server <white>» <gray><message><reset><newline>"
command-ping-self = "<prefix> <gray>Your connection latency is around <white><ping>ms.<gray>"
command-ping-other = "<prefix> <white><player><gray>'s connection latency is around <white><ping>ms<gray>."