name: Basics
version: '1.0'
main: com.spektrsoyuz.basics.BasicsPlugin
description: WIP
api-version: '1.21.4'
load: STARTUP
authors: [SpektrSoyuz]
dependencies:
  server:
    MiniPlaceholders:
      load: BEFORE
      required: false
      join-classpath: true