name: Basics
version: '1.0'
main: com.spektrsoyuz.basics.BasicsPlugin
description: A lightweight paper plugin that adds essential commands and features
api-version: '1.21.4'
load: STARTUP
authors: [ SpektrSoyuz ]
